package config

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strconv"

	log "github.com/sirupsen/logrus"
	"golang.org/x/crypto/pbkdf2"
)

const (
	// DefaultPort the default port
	DefaultPort = "3000"
	// DefaultDataDir default folder for storage
	DefaultDataDir = "data"

	// ReadStorageExpirationInMinutes time the token is valid
	ReadStorageExpirationInMinutes = 5
	// WriteStorageExpirationInMinutes time the token is valid
	WriteStorageExpirationInMinutes = 5

	// DefaultHost fake url
	DefaultHost = "local.appspot.com"

	// EnvLogLevel environment variable for the log level
	EnvLogLevel = "LOGLEVEL"
	// EnvLogFormat type of log format
	EnvLogFormat = "LOGFORMAT"
	// envDataDir
	envDataDir = "DATADIR"
	envPort    = "PORT"
	// EnvStorageURL the external name of the service
	EnvStorageURL = "STORAGE_URL"
	// envTLSCert the path of the cert file
	envTLSCert = "TLS_CERT"
	// envTLSKey the path of the private key
	envTLSKey = "TLS_KEY"

	// auth
	envJWTSecretKey     = "JWT_SECRET_KEY"
	envRegistrationOpen = "OPEN_REGISTRATION"

	// envAdminAPIToken static bearer token for the headless admin API
	envAdminAPIToken = "RM_ADMIN_API_TOKEN"

	// EnvLogFile log file to use
	EnvLogFile     = "RM_LOGFILE"
	envHTTPSCookie = "RM_HTTPS_COOKIE"
	envTrustProxy  = "RM_TRUST_PROXY"

	envMQTTPort          = "MQTT_PORT"
	envICEServers        = "ICE_SERVERS"
	envHashSchemaVersion = "HASH_SCHEMA_VERSION"
)

// Config config
type Config struct {
	Port       string
	StorageURL string
	//only https
	CloudHost         string
	DataDir           string
	RegistrationOpen  bool
	CreateFirstUser   bool
	AdminAPIToken     string
	JWTSecretKey      []byte
	JWTRandom         bool
	Certificate       tls.Certificate
	LogFile           string
	HTTPSCookie       bool
	TrustProxy        bool
	MQTTPort          string
	ICEServers        []interface{}
	HashSchemaVersion string
}

// Verify verify
func (cfg *Config) Verify() {
	if cfg.JWTRandom {
		log.Warn("The authentication will fail the next time you start the server!")
		log.Warnf("%s was not set! The following was autogenerated", envJWTSecretKey)
		log.Warnf("%s=%X", envJWTSecretKey, cfg.JWTSecretKey)
	}

	if !cfg.HTTPSCookie {
		log.Warnln(envHTTPSCookie + " is not set, use only when not using https!")
	}

	if cfg.Certificate.Certificate == nil {
		log.Info("For HTTPS, provide " + envTLSCert + " and " + envTLSKey)
	} else {
		log.Info("MQTT will use provided TLS certificate")
	}

	if len(cfg.ICEServers) > 0 {
		log.Infof("WebRTC configured with %d ICE server(s)", len(cfg.ICEServers))
	} else {
		log.Info("No ICE servers configured - screenshare will only work on local networks")
	}
}

// FromEnv config from environment values
func FromEnv() *Config {
	var err error
	var dataDir string
	data := os.Getenv(envDataDir)
	if data != "" {
		dataDir = data
	} else {
		dataDir, err = filepath.Abs(DefaultDataDir)
		if err != nil {
			log.Fatal("DataDir: ", err)
		}
	}

	port := os.Getenv(envPort)
	if port == "" {
		port = DefaultPort
	}

	jwtGenerated := false
	jwtSecretKey := []byte(os.Getenv(envJWTSecretKey))
	if len(jwtSecretKey) == 0 {
		jwtSecretKey = make([]byte, 32)
		_, err := rand.Read(jwtSecretKey)
		if err != nil {
			log.Fatal(err)
		}
		jwtGenerated = true
	}
	dk := pbkdf2.Key(jwtSecretKey, []byte("todo some salt"), 10000, 32, sha256.New)

	var cert tls.Certificate
	certPath := os.Getenv(envTLSCert)
	keyPath := os.Getenv(envTLSKey)
	if certPath != "" && keyPath != "" {

		cert, err = tls.LoadX509KeyPair(certPath, keyPath)
		if err != nil {
			log.Fatal("unable to load certificate:", err)
		}
	}
	openRegistration, _ := strconv.ParseBool(os.Getenv(envRegistrationOpen))
	httpsCookie, _ := strconv.ParseBool(os.Getenv(envHTTPSCookie))

	cloudHost := DefaultHost
	uploadURL := os.Getenv(EnvStorageURL)
	if uploadURL == "" {
		//it will go through the local proxy
		uploadURL = "https://" + DefaultHost
	} else {
		u, err := url.Parse(uploadURL)
		if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
			log.Fatalf("%s '%s' cannot be parsed, or missing scheme (http|https) %v", EnvStorageURL, uploadURL, err)
		}
		if u.Port() != "" {
			log.Warn(EnvStorageURL, " >= 3.15 doesnt support :port, only https, sync will fail!")
		}
		if u.Scheme != "https" {
			log.Warn(EnvStorageURL, " >= 3.15 only https is supported, sync fill fail!")
		}
		cloudHost = u.Host
	}

	trustProxy, _ := strconv.ParseBool(os.Getenv(envTrustProxy))

	mqttPort := os.Getenv(envMQTTPort)
	if mqttPort == "" {
		mqttPort = "8883"
	}

	var iceServers []interface{}
	iceServersJSON := os.Getenv(envICEServers)
	if iceServersJSON != "" {
		err := json.Unmarshal([]byte(iceServersJSON), &iceServers)
		if err != nil {
			log.Warnf("Failed to parse %s: %v", envICEServers, err)
			iceServers = nil
		}
	}
	if len(iceServers) == 0 {
		iceServers = []interface{}{
			map[string]string{"url": "stun:stun.l.google.com:19302", "username": "", "credential": ""},
		}
	}
	iceServers = normalizeICEServers(iceServers)

	hashSchemaVersion := os.Getenv(envHashSchemaVersion)
	if hashSchemaVersion == "" {
		hashSchemaVersion = "3"
	} else if hashSchemaVersion != "3" && hashSchemaVersion != "4" {
		log.Fatalf("%s must be either '3' or '4', got: %s", envHashSchemaVersion, hashSchemaVersion)
	}

	cfg := Config{
		Port:              port,
		StorageURL:        uploadURL,
		CloudHost:         cloudHost,
		DataDir:           dataDir,
		JWTSecretKey:      dk,
		JWTRandom:         jwtGenerated,
		Certificate:       cert,
		RegistrationOpen:  openRegistration,
		AdminAPIToken:     os.Getenv(envAdminAPIToken),
		HTTPSCookie:       httpsCookie,
		TrustProxy:        trustProxy,
		MQTTPort:          mqttPort,
		ICEServers:        iceServers,
		HashSchemaVersion: hashSchemaVersion,
	}
	return &cfg
}

// normalizeICEServers expands "urls" arrays into singular "url" entries; xochitl rejects anything else
func normalizeICEServers(servers []interface{}) []interface{} {
	normalized := make([]interface{}, 0, len(servers))
	for _, s := range servers {
		m, ok := toStringMap(s)
		if !ok {
			normalized = append(normalized, s)
			continue
		}
		_, hasURL := m["url"]
		_, hasURLs := m["urls"]
		urls := collectICEURLs(m)
		if len(urls) == 0 {
			if !hasURL && !hasURLs {
				normalized = append(normalized, s)
			}
			continue
		}
		for _, u := range urls {
			entry := map[string]interface{}{"url": u}
			for k, v := range m {
				if k == "url" || k == "urls" {
					continue
				}
				entry[k] = v
			}
			normalized = append(normalized, entry)
		}
	}
	return normalized
}

func toStringMap(v interface{}) (map[string]interface{}, bool) {
	switch t := v.(type) {
	case map[string]interface{}:
		return t, true
	case map[string]string:
		m := make(map[string]interface{}, len(t))
		for k, val := range t {
			m[k] = val
		}
		return m, true
	default:
		return nil, false
	}
}

func collectICEURLs(m map[string]interface{}) []string {
	var urls []string
	add := func(v interface{}) {
		switch t := v.(type) {
		case string:
			if t != "" {
				urls = append(urls, t)
			}
		case []interface{}:
			for _, item := range t {
				if str, ok := item.(string); ok && str != "" {
					urls = append(urls, str)
				}
			}
		}
	}
	add(m["url"])
	add(m["urls"])
	return urls
}

// EnvVars env vars usage
func EnvVars() string {
	return fmt.Sprintf(`
Environment Variables:

General:
	%s	Secret for signing JWT tokens
	%s	Url the tablet can resolve (default: %s)
			needs to be set to the hostname or proxy if behind a proxy
			especially if you want other tools to work (eg rmapi)

	%s	Log verbosity level (debug, info, warn) (default: info)
	%s	Log format: json (default: text)
	%s		Port (default: %s)
	%s		Local storage folder (default: %s)
	%s	Path to the server certificate.
	%s		Path to the server certificate key.
	%s	Write logs to file
	%s Send auth cookie only via https
	%s	Trust the proxy for X-Forwarded-For/X-Real-IP (set only if behind a proxy)
	%s	Hash tree schema version: "3" or "4" (default: 3)
	%s	Bearer token for the headless admin API (unset disables /admin routes)

MQTT (for screenshare):
	%s	MQTT TCP port (default: 8883)
	%s	ICE servers for WebRTC (JSON array format)
			Example: [{"urls":["stun:stun.l.google.com:19302"]}]
			With auth: [{"urls":["turn:server:port"],"username":"user","credential":"pass"}]
`,
		envJWTSecretKey,
		EnvStorageURL,
		DefaultHost,
		EnvLogLevel,
		EnvLogFormat,
		envPort,
		DefaultPort,
		envDataDir,
		DefaultDataDir,
		envTLSCert,
		envTLSKey,
		EnvLogFile,
		envHTTPSCookie,
		envTrustProxy,
		envHashSchemaVersion,
		envAdminAPIToken,

		envMQTTPort,
		envICEServers,
	)
}
