replicaCount: 1

image:
  repository: ddvk/rmfakecloud
  pullPolicy: Always
  tag: "latest"

rmfakecloud:
  # The secret key used to sign the authentication token. Generate with : openssl rand -base64 48
  jwt_secret_key: "WF1yQRu9blh4nPBzejnl8sgWCaVHvivyaOMcjmjxHSOka/Bd7dxPP6vObv81ThYI"
  # Optional bearer token that enables the headless admin JSON API (/admin). Leave empty to disable.
  rm_admin_api_token:
  rm_trust_proxy:
  rm_https_cookie: false
  # Your domaine name (ex: https://local.appspot.com ) 
  storage_url: "http://localhost:3000"

persistence:
  storageClassName: "longhorn"
  enabled: true 
  size: "5Gi"

# Don't touch these settings if you don't know what you're doing.
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: 
   limits:
     cpu: 100m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
